name: hph-vision
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python >=3.11,<4.0
  - nodejs
  - yarn
  - openjdk 17.*
  - poetry
  - pip
  - pip:
      - click
      - pre-commit
      - makim
