import React, {useMemo} from 'react';
import {Pressable, StyleSheet, Text, View} from 'react-native';
import {
  createRefractionSession,
  nextRefractionTrial,
  recordRefractionResponse,
  scoreRefractionSession,
  type BetterWorseSame,
  type OneTwoChoice,
} from '@hiperhealth/hphvision-lib';
import {InfoCard} from '../../components/feedback/InfoCard';
import {PrimaryButton} from '../../components/forms/PrimaryButton';
import {Screen} from '../../components/layout/Screen';
import {useHphVisionApp} from '../../state/sessionStore';
import {colors, radii, spacing, typography} from '../../theme';
import {formatDiopter, formatPercent} from '../../utils/format';

const sphericalAnswers: BetterWorseSame[] = [
  'better',
  'worse',
  'same',
  'unknown',
];
const comparisonAnswers: OneTwoChoice[] = ['one', 'two', 'same', 'unknown'];

export const RefractionTestScreen = () => {
  const {state, actions} = useHphVisionApp();
  const session = state.refractionSession;
  const currentTrial = useMemo(
    () => (session ? nextRefractionTrial(session) : undefined),
    [session],
  );
  const answeredCount = session?.responses.length ?? 0;
  const totalCount = session?.trials.length ?? 0;

  const startSession = () => {
    actions.saveRefractionSession(
      createRefractionSession({
        id: `${state.sessionId}-refraction-right`,
        eye: 'right',
        maxTrials: 6,
      }),
    );
  };

  const recordAnswer = (answer: BetterWorseSame | OneTwoChoice) => {
    if (!session || !currentTrial) {
      return;
    }

    const nextSession = recordRefractionResponse(session, {
      trialId: currentTrial.id,
      answer,
      inputMethod: 'touch',
      createdAt: new Date().toISOString(),
    });
    actions.saveRefractionSession(nextSession);
  };

  const scoreAndContinue = () => {
    if (!session) {
      return;
    }

    actions.saveRefractionResult(scoreRefractionSession(session));
    actions.navigate('results');
  };

  if (!session) {
    return (
      <Screen
        route="refractionTest"
        subtitle="Run a short subjective refraction prototype with touch responses.">
        <InfoCard
          title="Right-eye refraction prototype"
          body="The initial flow captures a compact comparison sequence. Future milestones can add left-eye routing, voice prompts, and previous-prescription seeding."
        />
        <PrimaryButton
          label="Start refraction prototype"
          onPress={startSession}
        />
        <PrimaryButton
          label="Skip to result summary"
          variant="secondary"
          onPress={() => actions.navigate('results')}
        />
      </Screen>
    );
  }

  if (!currentTrial) {
    const rightEye = state.refractionResult?.rightEye;

    return (
      <Screen
        route="refractionTest"
        subtitle="All refraction prompts have touch responses.">
        <InfoCard
          title="Refraction sequence complete"
          body={`${answeredCount} of ${totalCount} comparisons captured. Score the shared-library session to continue.`}
          tone="success"
        />
        {rightEye ? (
          <InfoCard
            title="Refraction estimate"
            body={`Sphere ${formatDiopter(
              rightEye.sphere,
            )}, cylinder ${formatDiopter(rightEye.cylinder)}, axis ${
              rightEye.axis ?? 'n/a'
            }, confidence ${formatPercent(
              state.refractionResult?.confidence ?? 0,
            )}.`}
          />
        ) : null}
        <PrimaryButton
          label="Score refraction and continue"
          onPress={scoreAndContinue}
        />
      </Screen>
    );
  }

  const answers =
    currentTrial.kind === 'sphericalComparison'
      ? sphericalAnswers
      : comparisonAnswers;

  return (
    <Screen
      route="refractionTest"
      subtitle="Choose which option looks better, or mark same/unknown when unsure.">
      <InfoCard
        title={currentTrial.kind}
        body={`Prompt ${
          answeredCount + 1
        } of ${totalCount}. Option deltas are generated by hphvision-lib.`}
      />
      <View style={styles.comparisonCard}>
        <View style={styles.optionCard}>
          <Text style={styles.optionTitle}>Option 1</Text>
          <Text style={styles.optionText}>
            Sphere {formatDiopter(currentTrial.optionA?.sphereDelta)}
          </Text>
          <Text style={styles.optionText}>
            Cylinder {formatDiopter(currentTrial.optionA?.cylinderDelta)}
          </Text>
          <Text style={styles.optionText}>
            Axis Δ {currentTrial.optionA?.axisDelta ?? 0}°
          </Text>
        </View>
        <View style={styles.optionCard}>
          <Text style={styles.optionTitle}>Option 2</Text>
          <Text style={styles.optionText}>
            Sphere {formatDiopter(currentTrial.optionB?.sphereDelta)}
          </Text>
          <Text style={styles.optionText}>
            Cylinder {formatDiopter(currentTrial.optionB?.cylinderDelta)}
          </Text>
          <Text style={styles.optionText}>
            Axis Δ {currentTrial.optionB?.axisDelta ?? 0}°
          </Text>
        </View>
      </View>
      <View style={styles.answerGrid}>
        {answers.map(answer => (
          <Pressable
            accessibilityRole="button"
            key={answer}
            onPress={() => recordAnswer(answer)}
            style={styles.answerButton}>
            <Text style={styles.answerText}>{answer}</Text>
          </Pressable>
        ))}
      </View>
      <Text style={styles.progressText}>
        Captured {answeredCount} / {totalCount} responses
      </Text>
    </Screen>
  );
};

const styles = StyleSheet.create({
  answerButton: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.md,
    borderWidth: 1,
    flexBasis: '45%',
    flexGrow: 1,
    paddingVertical: spacing.md,
  },
  answerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  answerText: {
    color: colors.text,
    fontSize: typography.body,
    fontWeight: '800',
    textTransform: 'capitalize',
  },
  comparisonCard: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  optionCard: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderRadius: radii.lg,
    borderWidth: 1,
    flex: 1,
    padding: spacing.lg,
  },
  optionText: {
    color: colors.textMuted,
    fontSize: typography.caption,
    lineHeight: 20,
  },
  optionTitle: {
    color: colors.text,
    fontSize: typography.subheading,
    fontWeight: '800',
    marginBottom: spacing.sm,
  },
  progressText: {
    color: colors.textMuted,
    fontSize: typography.caption,
    fontWeight: '700',
    textAlign: 'center',
  },
});
